--INSERT INTO idiomas(nombre) VALUES 
--("Spanish","es"),
--("German","de"),
--("English","en"),
--("French","fr");
--
--INSERT INTO peliculas(
--  oscar,
--  fecha_estreno,
--  duracion_minutos
--) VALUES (
--  -- Titanic
--  true,"1997-12-18",194
--),(
--  -- Star Wars IV
--  false,"1977-05-25",121
--),(
--  --Viaje de Chihiro
--  false,"2001-07-20",125
--),(
--  -- Inside Out
--  false,"1977-05-25",121
--),(
--)
--
--INSERT INTO titulos_de_peliculas(titulo) VALUES
--("Titanic"),
--("Star Wars: Episode IV - A New Hope"),
--("Star Wars: Episode IV – Eine neue Hoffnung"),
--("Star Wars, épisode IV : Un nouvel espoir"),
--("Spirited Away"),
--("Le Voyage de Chihiro"),
--("El viaje de Chihiro"),
--("Chihiros Reise ins Zauberland"),


-- Titanic (597)
--Star Wars: Episode IV – A New Hope (11)
--Spirited Away (129)
--Inside Out (59170)
--Braveheart (197)
--Back to the future (264)
--Forrest Gump (13)
--Who Framed Roger Rabbit (856)
--Indiana Jones and the Last Crusade (89)
--Jumanji (8844)
